@url_dev = http://localhost:8080/v1/api/
### Sign up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8

{
    "name": "shoplah1",
    "email": "shoplah1@gmail.com",
    "password": "123"
}

### Login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8

{
    "email": "shoplah@gmail.com",
    "password": "123"
}

### Log out
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhhNTg1MDcwOWU2NDhiOTcyYzU0NzgiLCJlbWFpbCI6InNob3BsYWgxQGdtYWlsLmNvbSIsImlhdCI6MTcyMDM0MjYwOCwiZXhwIjoxNzIwNTE1NDA4fQ.Tuv2-I1F1LEwEbpxjRiRmcoAB4PhpVUARmLMLiMnL-0
x-client-id: 668a5850709e648b972c5478

### Handle Refresh Token
POST {{url_dev}}/shop/handleRefreshToken
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIwMzUyMDY0LCJleHAiOjE3MjA1MjQ4NjR9.gW4RrZtISuZhH0cte4x16vjSI8B1ZYxQmiUbQpiVCug
x-client-id: 6688f3c3faef8c441494d74c

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIwMzUyMDY0LCJleHAiOjE3MjA5NTY4NjR9.Pxn_UXrs2mPvbRDnp_0ct5YojaoeqJg_W0Vwwfdz1MI"
}

### Handle Refresh Token V2
POST {{url_dev}}/shop/handleRefreshTokenV2
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
x-client-id: 6688f3c3faef8c441494d74c
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIwNDM5MjAwLCJleHAiOjE3MjEwNDQwMDB9.2CtOiTtEDfIUmUGQBFP8uK2EszAbXOi6snByiBa_Ky8

### Create product cloth
POST {{url_dev}}product
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIwOTM0MDk3LCJleHAiOjE3MjExMDY4OTd9.SYKjWcKQE67HOI_j8EgmQPB2-tGeRAnKMqIPVYeY1W8
x-client-id: 6688f3c3faef8c441494d74c

{
    "product_name": "Trouser",
    "product_thumb": "product thumb",
    "product_description": "High quality",
    "product_price": 50,
    "product_quantity": 100,
    "product_type": "Clothing",
    "product_attributes": {
        "brand": "Lele",
        "size": "L",
        "material": "Cotton"
    }
}

### Create product electronic
POST {{url_dev}}product
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIyNTAxODUyLCJleHAiOjE3MjI2NzQ2NTJ9.Euj3AMNeHXnYMnjXEhzUlwrL-DJbG5RH4liiZKB8hh0
x-client-id: 6688f3c3faef8c441494d74c

{
    "product_name": "Iphone 69",
    "product_description": "High-end",
    "product_price": 100,
    "product_quantity": 1,
    "product_thumb": "product thumb",
    "product_type": "Electronic",
    "product_attributes": {
        "manufacturer": "Apple",
        "model": "Ip69",
        "color": "Dark green"
    }
}
### Create product furniture
POST {{url_dev}}product
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIwNDM5MjMyLCJleHAiOjE3MjA2MTIwMzJ9.p5M8a7S0wJZLTZyT5LA5CKDgVpU7hLE33ASWo1KElq8
x-client-id: 6688f3c3faef8c441494d74c

{
    "product_name": "Desk",
    "product_description": "High quality",
    "product_price": 50,
    "product_quantity": 5,
    "product_thumb": "product thumb",
    "product_type": "Furniture",
    "product_attributes": {
        "brand": "Wellknown",
        "size": "L",
        "material": "Wood"
    }
}

### Get drafts list
GET {{url_dev}}product/drafts/all
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIwNjkwNjIwLCJleHAiOjE3MjA4NjM0MjB9.IbCLv-MNLdLZJ8f-FLv7W4m5mxjnXquvGLdeYoo7Q-E
x-client-id: 6688f3c3faef8c441494d74c

### Get published list
GET {{url_dev}}product/published/all
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIwNjkwNjIwLCJleHAiOjE3MjA4NjM0MjB9.IbCLv-MNLdLZJ8f-FLv7W4m5mxjnXquvGLdeYoo7Q-E
x-client-id: 6688f3c3faef8c441494d74c

### Publish Product
POST {{url_dev}}product/publish/668fa90aebef6b38a1db4805
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIwNjkwNjIwLCJleHAiOjE3MjA4NjM0MjB9.IbCLv-MNLdLZJ8f-FLv7W4m5mxjnXquvGLdeYoo7Q-E
x-client-id: 6688f3c3faef8c441494d74c

### Search Product
GET {{url_dev}}product/search/11
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8

### Get all product
GET {{url_dev}}product/
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8

### Get Product
GET {{url_dev}}product/668fa90aebef6b38a1db4805
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8

### Create product cloth
PATCH {{url_dev}}product/668fa90aebef6b38a1db4805
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIwOTM0MDk3LCJleHAiOjE3MjExMDY4OTd9.SYKjWcKQE67HOI_j8EgmQPB2-tGeRAnKMqIPVYeY1W8
x-client-id: 6688f3c3faef8c441494d74c

{
    "product_name": "New_Hanni",
    "product_type": "Clothing",
    "product_attributes": {
        "brand": "Levia"
    }
}

### Create discount code
POST {{url_dev}}discount
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIxMjAzNDEyLCJleHAiOjE3MjEzNzYyMTJ9.pB2W4Wl32Veaj5eHfTBLUOu6paSAv9rsXeQMRmjIXaY
x-client-id: 6688f3c3faef8c441494d74c

{
    "name": "name fixed amount",
    "description": "desc",
    "type": "percentage",
    "value": 20,
    "max_value": 3000,
    "code": "SHOP-1122",
    "start_date": "2024-04-15 09:00:00",
    "end_date": "2024-08-15 09:00:00",
    "max_uses": 100,
    "uses_count": 0,
    "users_used": [],
    "max_uses_per_user": 1,
    "min_order_value": 100,
    "create_by": {},
    "shopId": "",
    "is_active": true,
    "applies_to": "specific",
    "product_ids": ["668e5ad86fcba09c87b4bfc0", "668fa90aebef6b38a1db4805"]
}

### List product code
GET {{url_dev}}discount/list_product_code?code=SHOP-1122&shopId=6688f3c3faef8c441494d74c&limit=50&page=1
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8

### List discount by shop
GET {{url_dev}}discount?shopId=6688f3c3faef8c441494d74c&limit=50&page=1
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIxODg3NDgzLCJleHAiOjE3MjIwNjAyODN9.ZkSRhWZGQajzF_RCZLoHLHfetWYRhUgvyyiINV19wi0
x-client-id: 6688f3c3faef8c441494d74c

### Discount amount
POST {{url_dev}}discount/amount
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIxODg3NDgzLCJleHAiOjE3MjIwNjAyODN9.ZkSRhWZGQajzF_RCZLoHLHfetWYRhUgvyyiINV19wi0
x-client-id: 6688f3c3faef8c441494d74c

{
    "codeId": "SHOP-1122",
    "userId": 2,
    "shopId": "6688f3c3faef8c441494d74c",
    "products": [{
        "productId": "668fa90aebef6b38a1db4805",
        "quantity": 5,
        "price": 120000
    }
    ]
}

### Discount amount
POST {{url_dev}}cart
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIxODg3NDgzLCJleHAiOjE3MjIwNjAyODN9.ZkSRhWZGQajzF_RCZLoHLHfetWYRhUgvyyiINV19wi0
x-client-id: 6688f3c3faef8c441494d74c

{
    "userId": 1001,
    "product": {
        "productId": "668fa90aebef6b38a1db4805",
        "shopId": "6688f3c3faef8c441494d74c",
        "name": "",
        "quantity": 5,
        "price": 1234
    }
}

### Discount amount
DELETE {{url_dev}}cart
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIxODg3NDgzLCJleHAiOjE3MjIwNjAyODN9.ZkSRhWZGQajzF_RCZLoHLHfetWYRhUgvyyiINV19wi0
x-client-id: 6688f3c3faef8c441494d74c

{
    "userId": 1001,
    "productId": "668fa90aebef6b38a1db4805"
}

### Discount amount
GET  {{url_dev}}cart?userId=1001
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIxODg3NDgzLCJleHAiOjE3MjIwNjAyODN9.ZkSRhWZGQajzF_RCZLoHLHfetWYRhUgvyyiINV19wi0
x-client-id: 6688f3c3faef8c441494d74c

### UpdateCart
POST {{url_dev}}cart/update
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIxODg3NDgzLCJleHAiOjE3MjIwNjAyODN9.ZkSRhWZGQajzF_RCZLoHLHfetWYRhUgvyyiINV19wi0
x-client-id: 6688f3c3faef8c441494d74c

{
    "userId": 1001,
    "shop_order_ids":[ {
        "shopId": "6688f3c3faef8c441494d74c",
        "item_products": [{
            "shopId": "6688f3c3faef8c441494d74c",
            "productId": "668fa90aebef6b38a1db4805",
            "quantity": 10,
            "old_quantity": 8,
            "price": 1234
        }]
    }]
}

### Review
POST {{url_dev}}checkout/review
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIxODg3NDgzLCJleHAiOjE3MjIwNjAyODN9.ZkSRhWZGQajzF_RCZLoHLHfetWYRhUgvyyiINV19wi0
x-client-id: 6688f3c3faef8c441494d74c

{
    "userId": 1001,
    "cartId": "66a2196abdc2a9fe9025ccea",
    "shop_order_ids":[ {
        "shopId": "6688f3c3faef8c441494d74c",
        "shop_discounts": [{
            "shop_id": "6688f3c3faef8c441494d74c",
            "discountId": "66977b094180f628fda2a578",
            "codeId": "SHOP-1122"
        }],
        "item_products": [{
            "productId": "668fa90aebef6b38a1db4805",
            "quantity": 2,
            "price": 10000
        }]
    }]
}

### Create comment
POST {{url_dev}}comment
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIyNTAxODUyLCJleHAiOjE3MjI2NzQ2NTJ9.Euj3AMNeHXnYMnjXEhzUlwrL-DJbG5RH4liiZKB8hh0
x-client-id: 6688f3c3faef8c441494d74c

{
    "productId": "668fa90aebef6b38a1db4805",
    "userId": 1001,
    "content": "comment 1.2.1.2",
    "parentCommentId": "66ab526b904baeafa2c28e0d"
}

### Get comments by parent Id
GET {{url_dev}}comment?productId=668fa90aebef6b38a1db4805&parentCommentId=66ab4de017e1c6e85e80db67
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIyNTAxODUyLCJleHAiOjE3MjI2NzQ2NTJ9.Euj3AMNeHXnYMnjXEhzUlwrL-DJbG5RH4liiZKB8hh0
x-client-id: 6688f3c3faef8c441494d74c

### Delete comment
DELETE {{url_dev}}comment
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIyNTAxODUyLCJleHAiOjE3MjI2NzQ2NTJ9.Euj3AMNeHXnYMnjXEhzUlwrL-DJbG5RH4liiZKB8hh0
x-client-id: 6688f3c3faef8c441494d74c

{
    "productId": "668fa90aebef6b38a1db4805",
    "commentId": "66ab520d904baeafa2c28df8"
}

### Get notifications
GET {{url_dev}}notification
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIyNTAxODUyLCJleHAiOjE3MjI2NzQ2NTJ9.Euj3AMNeHXnYMnjXEhzUlwrL-DJbG5RH4liiZKB8hh0
x-client-id: 6688f3c3faef8c441494d74c

### Upload image by url
POST {{url_dev}}upload/product
Content-Type: application/json
x-api-key: 895ecdf54bd5bdd057db65b231f02416f02c373ef9cb088ac0c6846b4d6fbb28d040d3dfacff682e10c24e4abad1bc8d521f142a59ee64310178924847d345e8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4ZjNjM2ZhZWY4YzQ0MTQ5NGQ3NGMiLCJlbWFpbCI6InNob3BsYWhAZ21haWwuY29tIiwiaWF0IjoxNzIyNTAxODUyLCJleHAiOjE3MjI2NzQ2NTJ9.Euj3AMNeHXnYMnjXEhzUlwrL-DJbG5RH4liiZKB8hh0
x-client-id: 6688f3c3faef8c441494d74c